# Generated by Django 6.0.4 on 2026-05-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('on_way', 'В пути'), ('done', 'Завершён')], default='new', max_length=20),
        ),
    ]
