# Generated by Django 6.0.4 on 2026-06-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_order_options_order_driver_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Расстояние (км)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tariff',
            field=models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес')], default='economy', max_length=20, verbose_name='Тариф'),
        ),
    ]
