# Generated by Django 6.0.4 on 2026-06-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_order_distance_km_order_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Водитель'),
        ),
    ]
