# Generated by Django 6.0.4 on 2026-07-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paymentcard'),
        ('taxi', '0006_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.paymentcard', verbose_name='Карта оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], default='cash', max_length=10, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('accepted', 'Водитель едет'), ('arrived', 'На месте'), ('on_way', 'В пути'), ('done', 'Завершён'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff',
            field=models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('cargo', 'Грузовой'), ('pets', 'С животными'), ('kids', 'С детьми')], default='economy', max_length=20, verbose_name='Тариф'),
        ),
    ]
