# Generated by Django 6.0.4 on 2026-07-05 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_dispatcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('apple_pay', 'Apple Pay')], default='visa', max_length=20, verbose_name='Тип')),
                ('last4', models.CharField(max_length=4, verbose_name='Последние 4 цифры')),
                ('exp_month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('exp_year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('holder_name', models.CharField(blank=True, max_length=100, verbose_name='Имя на карте')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платёжная карта',
                'verbose_name_plural': 'Платёжные карты',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
